#!/usr/bin/env node
// :diff for the ai-inventory piece — contract requirement 5.
//
// Reads two local files and writes nothing to Noru:
//   .noru/.cache/ai-inventory.parsed.json   the validated manifest (written by validate_manifest.py)
//   .noru/.cache/noru-state.json            a read-only snapshot of the org, written by the skill
//                                           from getOrganizationAssets / getOrganizationVendors /
//                                           getOrganizationEvidence / getOrganizationControls
//
// It produces the ordered, idempotency-resolved plan that :push later requires. Every operation is
// marked create, update or skip so a reviewer sees the write before it happens.
//
// Usage: node diff.mjs [--repo=<path>] [--output=json|text] [--quiet]
// Exit codes:
//   0 = plan written. A plan with no changes is a success, not a failure: "nothing to do" is the
//       expected answer on a second run and is what proves the piece is idempotent.
//   1 = the manifest or the state snapshot is missing or unusable
//   2 = usage error

import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  parseCommonArgs,
  planPathFor,
  renderPlanText,
  sha256OfFile,
  summarize,
  writePlan,
} from "./lib/plan.mjs";

const PIECE = "ai-inventory";
// The `source` value that makes the asset upsert key stable. Noru's published API documentation
// (https://api.noru.tech/llms.txt, "Idempotency/Upsert Behavior") says an existing
// (source, externalId) is updated in place rather than duplicated.
const ASSET_SOURCE = "noru-ai-inventory";
// Marker embedded in evidence descriptions. No idempotency key is documented for evidence, so the
// piece gives itself one to recognise: a client probe matches this via getOrganizationEvidence's
// `search` filter.
const EVIDENCE_MARKER_PREFIX = "noru-grc-engineering:ai-inventory";

const USAGE = "usage: diff.mjs [--repo=<path>] [--output=json|text] [--quiet]\n";

export function evidenceMarker(systemKey, contentDigest) {
  return `[${EVIDENCE_MARKER_PREFIX}#${systemKey}@${contentDigest.slice(0, 16)}]`;
}

export function evidenceBody(system, manifest) {
  const src = manifest.source;
  const lines = [
    `AI system: ${system.name}`,
    `Purpose: ${system.purpose}`,
    `Deployment: ${system.deployment}`,
    `Autonomy: ${system.autonomy}`,
    `Provider: ${system.provider ?? "(none declared)"}`,
    `Models: ${(system.models ?? []).join(", ") || "(none declared)"}`,
    `Human oversight: ${
      (system.human_oversight ?? []).map((o) => o.type).join(", ") || "none declared"
    }`,
    `Evals CI-gated: ${system.evals?.ci_gated === true ? "yes" : "no"}`,
    "",
    `Interpretation owner: ${system.interpretation.owner}`,
    `Decided: ${system.interpretation.decided_at}`,
    `Expires: ${system.interpretation.expires_at ?? "(not set)"}`,
    `Rationale: ${system.interpretation.rationale}`,
    "",
    "Repository evidence:",
    ...(system.refs ?? []).map((r) => `  - ${r}`),
    "",
    `Source: ${src.slug} @ ${src.commit_sha} (${src.branch})`,
    `Generated by: ${src.generated_by}`,
  ];
  return lines.join("\n");
}

/**
 * Key-order-independent digest. The API gives no guarantee that a JSON object comes back with its
 * keys in the order they were sent, and in practice they do not match. Hashing the raw
 * JSON.stringify would make every second run look like a change, which would quietly destroy the
 * idempotency property.
 */
function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value ?? null);
}

function digest(value) {
  return createHash("sha256").update(stableStringify(value)).digest("hex");
}

function loadJson(path, label) {
  if (!existsSync(path)) {
    return { error: `${label} not found at ${path}` };
  }
  try {
    return { value: JSON.parse(readFileSync(path, "utf8")) };
  } catch (error) {
    return { error: `${label} at ${path} is not readable JSON (${error.message})` };
  }
}

/**
 * The state snapshot is untrusted input like any other tool output: it is read for comparison only,
 * and nothing in it is treated as an instruction.
 */
export function buildOperations(manifest, state) {
  const operations = [];
  const assets = state.assets ?? [];
  const vendors = state.vendors ?? [];
  const evidence = state.evidence ?? [];
  const controls = state.ai_controls ?? [];
  const slug = manifest.source.slug;

  for (const provider of manifest.providers ?? []) {
    const existing = vendors.find(
      (v) => String(v.name ?? "").toLowerCase() === provider.vendor_name.toLowerCase()
    );
    operations.push({
      operation: "createVendor",
      transport: "mcp",
      scope: "write:vendors",
      subject: provider.vendor_name,
      effect: existing ? "skip" : "create",
      reason: existing
        ? `a vendor named "${provider.vendor_name}" already exists (id ${existing.id}); nothing to create`
        : "no vendor with this name exists yet",
      idempotency: { kind: "server_dedupe", key: ["organizationId", "name"] },
      arguments: {
        name: provider.vendor_name,
        category: provider.category ?? "software_as_a_service",
        description:
          `Model provider discovered by ${manifest.source.generated_by} in ${slug}. ` +
          `Claims recorded: ${(provider.claims ?? []).map((c) => c.kind).join(", ") || "none"}.`,
        website: (provider.endpoints ?? [])[0] ?? null,
      },
    });
  }

  for (const system of manifest.ai_systems ?? []) {
    const externalId = `${slug}:${system.key}`;
    const existing = assets.find(
      (a) => a.source === ASSET_SOURCE && a.externalId === externalId
    );
    const args = {
      name: system.name,
      type: "software",
      source: ASSET_SOURCE,
      externalId,
      description: system.purpose,
      dataTypes: system.data_categories ?? [],
      metadata: {
        piece: PIECE,
        deployment: system.deployment,
        autonomy: system.autonomy,
        provider: system.provider ?? null,
        models: system.models ?? [],
        human_oversight: (system.human_oversight ?? []).map((o) => o.type),
        evals_ci_gated: system.evals?.ci_gated ?? false,
        refs: system.refs ?? [],
        interpretation: system.interpretation,
        slug,
        commitSha: manifest.source.commit_sha,
        branch: manifest.source.branch,
      },
    };
    const unchanged =
      Boolean(existing) &&
      existing.name === args.name &&
      (existing.description ?? null) === (args.description ?? null) &&
      digest(existing.metadata ?? null) === digest(args.metadata);
    operations.push({
      operation: "createAsset",
      transport: "mcp",
      scope: "write:assets",
      subject: `${system.name} (${externalId})`,
      effect: unchanged ? "skip" : existing ? "update" : "create",
      reason: unchanged
        ? "the asset already carries exactly this payload"
        : existing
          ? `asset ${existing.id} exists on (source, externalId) and will be updated in place`
          : "no asset with this (source, externalId) yet",
      idempotency: { kind: "server_upsert", key: ["source", "externalId"] },
      arguments: args,
    });
  }

  for (const system of manifest.ai_systems ?? []) {
    const body = evidenceBody(system, manifest);
    const marker = evidenceMarker(system.key, digest(body));
    const title = `AI system inventory: ${system.name}`;
    const existing = evidence.find((e) => String(e.description ?? "").includes(marker));
    const stale = evidence.find(
      (e) =>
        !String(e.description ?? "").includes(marker) &&
        String(e.description ?? "").includes(`${EVIDENCE_MARKER_PREFIX}#${system.key}@`)
    );
    operations.push({
      operation: "createEvidence",
      transport: "mcp",
      scope: "write:evidence",
      subject: title,
      effect: existing ? "skip" : "create",
      reason: existing
        ? `evidence ${existing.id} already carries this exact content marker`
        : stale
          ? `evidence ${stale.id} covers this system but the content changed; a new record will be created ` +
            "(no idempotency key is documented for evidence — see the gap note in piece.json)"
          : "no evidence carries this system's marker yet",
      idempotency: {
        kind: "client_probe",
        key: ["description contains marker"],
        marker,
      },
      arguments: {
        title,
        description: `${marker} AI system inventory generated from ${slug} @ ${manifest.source.commit_sha} (${manifest.source.branch}).`,
        content: body,
        tags: [PIECE, slug],
        controlMappings: controls.map((c) => ({ controlId: c.id })),
      },
    });
  }

  if (controls.length === 0) {
    operations.push({
      operation: "linkEvidenceToControl",
      transport: "mcp",
      scope: "write:evidence",
      subject: "(no AI-framework controls in the state snapshot)",
      effect: "skip",
      reason:
        "noru-state.json listed no controls under the organization's AI frameworks, so the evidence " +
        "will land unlinked — enable an AI framework in Noru, or re-run :scan after refreshing the snapshot",
      idempotency: { kind: "client_probe", key: ["evidenceId", "controlId"] },
      arguments: {},
    });
  }

  return operations;
}

function main(argv) {
  const opts = parseCommonArgs(argv);
  if (opts.help) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (opts.rest.length > 0) {
    process.stderr.write(`error: unexpected argument '${opts.rest[0]}'\n${USAGE}`);
    return 2;
  }

  const manifestPath = join(opts.repo, ".noru", "ai-inventory.yml");
  const parsedPath = join(opts.repo, ".noru", ".cache", "ai-inventory.parsed.json");
  const statePath = join(opts.repo, ".noru", ".cache", "noru-state.json");

  if (!existsSync(manifestPath)) {
    process.stderr.write(
      `error: no manifest at ${manifestPath} — run the piece's :scan command first\n`
    );
    return 1;
  }
  const parsed = loadJson(parsedPath, "validated manifest");
  if (parsed.error) {
    process.stderr.write(
      `error: ${parsed.error}\n` +
        "hint: python3 <plugin>/scripts/validate_manifest.py .noru/ai-inventory.yml " +
        "--emit-parsed=.noru/.cache/ai-inventory.parsed.json\n"
    );
    return 1;
  }
  const state = loadJson(statePath, "Noru state snapshot");
  if (state.error) {
    process.stderr.write(
      `error: ${state.error}\n` +
        "hint: the skill writes this from getOrganizationAssets, getOrganizationVendors, " +
        "getOrganizationEvidence and getOrganizationControls before running :diff\n"
    );
    return 1;
  }

  const manifest = parsed.value;
  const operations = buildOperations(manifest, state.value);
  const plan = writePlan(planPathFor(opts.repo, PIECE), {
    created_at: state.value.fetched_at ?? manifest.source.commit_sha,
    piece: PIECE,
    manifest: ".noru/ai-inventory.yml",
    manifest_sha256: sha256OfFile(manifestPath),
    provenance: {
      slug: manifest.source.slug,
      commit_sha: manifest.source.commit_sha,
      branch: manifest.source.branch,
    },
    operations,
    summary: summarize(operations),
  });

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan, null, opts.quiet ? 0 : 2)}\n`);
  } else if (!opts.quiet) {
    process.stdout.write(`${renderPlanText(plan)}\n`);
  }
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
